//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhSachPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danhSachPhong()
        {
            this.datPhongs = new HashSet<datPhong>();
        }
    
        public int maPhong { get; set; }
        public string tenPhong { get; set; }
        public string loaiPhong { get; set; }
        public Nullable<int> maKhachsan { get; set; }
        public string mieuTaPhong { get; set; }
        public string tinhTrangPhong { get; set; }
        public Nullable<decimal> giaPhong { get; set; }
    
        public virtual thongTinKhachSan thongTinKhachSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datPhong> datPhongs { get; set; }
    }
}
