//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHUNAM
    {
        public int MaThang { get; set; }
        public string TenThang { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string GhiChu { get; set; }
    }
}
