//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoaDon
    {
        public int maHoaDon { get; set; }
        public Nullable<int> maDatPhong { get; set; }
        public byte[] ngayThanhToan { get; set; }
        public Nullable<decimal> soTien { get; set; }
        public Nullable<int> maKieuThanhToan { get; set; }
        public string ghiChu { get; set; }
    
        public virtual datPhong datPhong { get; set; }
        public virtual kieuThanhToan kieuThanhToan { get; set; }
    }
}
