//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYKHACHSANEntities : DbContext
    {
        public QUANLYKHACHSANEntities()
            : base("name=QUANLYKHACHSANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<danhSachPhong> danhSachPhongs { get; set; }
        public virtual DbSet<datPhong> datPhongs { get; set; }
        public virtual DbSet<hoaDon> hoaDons { get; set; }
        public virtual DbSet<khachHang> khachHangs { get; set; }
        public virtual DbSet<kieuThanhToan> kieuThanhToans { get; set; }
        public virtual DbSet<loaiTheKhachHang> loaiTheKhachHangs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<theKhachHang> theKhachHangs { get; set; }
        public virtual DbSet<thongTinKhachSan> thongTinKhachSans { get; set; }
    }
}
