//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongTinKhachSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thongTinKhachSan()
        {
            this.danhSachPhongs = new HashSet<danhSachPhong>();
        }
    
        public int maKhachSan { get; set; }
        public string tenKhachSan { get; set; }
        public Nullable<double> soSao { get; set; }
        public string diaChi { get; set; }
        public string mieuTaKhachSan { get; set; }
        public Nullable<int> soPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danhSachPhong> danhSachPhongs { get; set; }
    }
}
